In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_profiling
%matplotlib inline
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
names=["duration","protocol_type","service","flag","src_bytes","dst_bytes","land", "wrong_fragment","urgent","hot",
       "num_failed_logins","logged_in", "num_compromised","root_shell","su_attempted","num_root","num_file_creations", 
       "num_shells","num_access_files","num_outbound_cmds","is_host_login", "is_guest_login","count","srv_count",
       "serror_rate", "srv_serror_rate", "rerror_rate","srv_rerror_rate","same_srv_rate", "diff_srv_rate", 
       "srv_diff_host_rate","dst_host_count","dst_host_srv_count","dst_host_same_srv_rate", "dst_host_diff_srv_rate",
       "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
       "dst_host_rerror_rate","dst_host_srv_rerror_rate","attack"] 
train_df=pd.read_csv('/content/drive/My Drive/Data/KDDTrain+_2.csv', names = names)

In [6]:
train_df.head()

   duration protocol_type  ... dst_host_srv_rerror_rate   attack
0         0           tcp  ...                     0.00   normal
1         0           udp  ...                     0.00   normal
2         0           tcp  ...                     0.00  neptune
3         0           tcp  ...                     0.01   normal
4         0           tcp  ...                     0.00   normal

[5 rows x 42 columns]

In [7]:
train_df.shape

(125973, 42)

In [9]:
test_df=pd.read_csv('/content/drive/My Drive/Data/KDDTest+_2.csv', names = names)

In [10]:
test_df.shape

(22544, 42)

In [11]:
train_df.head()

   duration protocol_type  ... dst_host_srv_rerror_rate   attack
0         0           tcp  ...                     0.00   normal
1         0           udp  ...                     0.00   normal
2         0           tcp  ...                     0.00  neptune
3         0           tcp  ...                     0.01   normal
4         0           tcp  ...                     0.00   normal

[5 rows x 42 columns]

In [12]:
test_df.head()

   duration protocol_type  ... dst_host_srv_rerror_rate   attack
0         0           tcp  ...                     1.00  neptune
1         0           tcp  ...                     1.00  neptune
2         2           tcp  ...                     0.00   normal
3         0          icmp  ...                     0.00    saint
4         1           tcp  ...                     0.71    mscan

[5 rows x 42 columns]

In [13]:
#Checking data types of varaibles,missing value presence and no, of each data type
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     125973 non-null  int64
 1   protocol_type                125973 non-null  object
 2   service                      125973 non-null  object
 3   flag                         125973 non-null  object
 4   src_bytes                    125973 non-null  int64
 5   dst_bytes                    125973 non-null  int64
 6   land                         125973 non-null  int64
 7   wrong_fragment               125973 non-null  int64
 8   urgent                       125973 non-null  int64
 9   hot                          125973 non-null  int64
 10  num_failed_logins            125973 non-null  int64
 11  logged_in                    125973 non-null  int64
 12  num_compromised              125973 non-null  int64
 13  root_shell                   125973 non-null  int64
 14  su_attempted                 125973 non-null  int64
 15  num_root                     125973 non-null  int64
 16  num_file_creations           125973 non-null  int64
 17  num_shells                   125973 non-null  int64
 18  num_access_files             125973 non-null  int64
 19  num_outbound_cmds            125973 non-null  int64
 20  is_host_login                125973 non-null  int64
 21  is_guest_login               125973 non-null  int64
 22  count                        125973 non-null  int64
 23  srv_count                    125973 non-null  int64
 24  serror_rate                  125973 non-null  float64
 25  srv_serror_rate              125973 non-null  float64
 26  rerror_rate                  125973 non-null  float64
 27  srv_rerror_rate              125973 non-null  float64
 28  same_srv_rate                125973 non-null  float64
 29  diff_srv_rate                125973 non-null  float64
 30  srv_diff_host_rate           125973 non-null  float64
 31  dst_host_count               125973 non-null  int64
 32  dst_host_srv_count           125973 non-null  int64
 33  dst_host_same_srv_rate       125973 non-null  float64
 34  dst_host_diff_srv_rate       125973 non-null  float64
 35  dst_host_same_src_port_rate  125973 non-null  float64
 36  dst_host_srv_diff_host_rate  125973 non-null  float64
 37  dst_host_serror_rate         125973 non-null  float64
 38  dst_host_srv_serror_rate     125973 non-null  float64
 39  dst_host_rerror_rate         125973 non-null  float64
 40  dst_host_srv_rerror_rate     125973 non-null  float64
 41  attack                       125973 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 40.4+ MB

In [14]:
#Checking train data for presence of missing values
train_df.isnull().any().value_counts()

False    42
dtype: int64

In [15]:
#Calculating general statistics for the train data to get insights about the data
train_df.describe(percentiles=[0.01,0.05,0.1,0.2,0.25,0.5,0.75,0.9,0.95,0.99]).T

                                count          mean  ...       99%           max
duration                     125973.0    287.144650  ...   9590.56  4.290800e+04
src_bytes                    125973.0  45566.743000  ...  54540.00  1.379964e+09
dst_bytes                    125973.0  19779.114421  ...  25519.00  1.309937e+09
land                         125973.0      0.000198  ...      0.00  1.000000e+00
wrong_fragment               125973.0      0.022687  ...      0.00  3.000000e+00
urgent                       125973.0      0.000111  ...      0.00  3.000000e+00
hot                          125973.0      0.204409  ...      3.00  7.700000e+01
num_failed_logins            125973.0      0.001222  ...      0.00  5.000000e+00
logged_in                    125973.0      0.395736  ...      1.00  1.000000e+00
num_compromised              125973.0      0.279250  ...      1.00  7.479000e+03
root_shell                   125973.0      0.001342  ...      0.00  1.000000e+00
su_attempted                 125973.0      0.001103  ...      0.00  2.000000e+00
num_root                     125973.0      0.302192  ...      0.00  7.468000e+03
num_file_creations           125973.0      0.012669  ...      0.00  4.300000e+01
num_shells                   125973.0      0.000413  ...      0.00  2.000000e+00
num_access_files             125973.0      0.004096  ...      0.00  9.000000e+00
num_outbound_cmds            125973.0      0.000000  ...      0.00  0.000000e+00
is_host_login                125973.0      0.000008  ...      0.00  1.000000e+00
is_guest_login               125973.0      0.009423  ...      0.00  1.000000e+00
count                        125973.0     84.107555  ...    511.00  5.110000e+02
srv_count                    125973.0     27.737888  ...    492.00  5.110000e+02
serror_rate                  125973.0      0.284485  ...      1.00  1.000000e+00
srv_serror_rate              125973.0      0.282485  ...      1.00  1.000000e+00
rerror_rate                  125973.0      0.119958  ...      1.00  1.000000e+00
srv_rerror_rate              125973.0      0.121183  ...      1.00  1.000000e+00
same_srv_rate                125973.0      0.660928  ...      1.00  1.000000e+00
diff_srv_rate                125973.0      0.063053  ...      1.00  1.000000e+00
srv_diff_host_rate           125973.0      0.097322  ...      1.00  1.000000e+00
dst_host_count               125973.0    182.148945  ...    255.00  2.550000e+02
dst_host_srv_count           125973.0    115.653005  ...    255.00  2.550000e+02
dst_host_same_srv_rate       125973.0      0.521242  ...      1.00  1.000000e+00
dst_host_diff_srv_rate       125973.0      0.082951  ...      1.00  1.000000e+00
dst_host_same_src_port_rate  125973.0      0.148379  ...      1.00  1.000000e+00
dst_host_srv_diff_host_rate  125973.0      0.032542  ...      0.52  1.000000e+00
dst_host_serror_rate         125973.0      0.284452  ...      1.00  1.000000e+00
dst_host_srv_serror_rate     125973.0      0.278485  ...      1.00  1.000000e+00
dst_host_rerror_rate         125973.0      0.118832  ...      1.00  1.000000e+00
dst_host_srv_rerror_rate     125973.0      0.120240  ...      1.00  1.000000e+00

[38 rows x 15 columns]

**EDA for Test data**

In [16]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22544 entries, 0 to 22543
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   duration                     22544 non-null  int64
 1   protocol_type                22544 non-null  object
 2   service                      22544 non-null  object
 3   flag                         22544 non-null  object
 4   src_bytes                    22544 non-null  int64
 5   dst_bytes                    22544 non-null  int64
 6   land                         22544 non-null  int64
 7   wrong_fragment               22544 non-null  int64
 8   urgent                       22544 non-null  int64
 9   hot                          22544 non-null  int64
 10  num_failed_logins            22544 non-null  int64
 11  logged_in                    22544 non-null  int64
 12  num_compromised              22544 non-null  int64
 13  root_shell                   22544 non-null  int64
 14  su_attempted                 22544 non-null  int64
 15  num_root                     22544 non-null  int64
 16  num_file_creations           22544 non-null  int64
 17  num_shells                   22544 non-null  int64
 18  num_access_files             22544 non-null  int64
 19  num_outbound_cmds            22544 non-null  int64
 20  is_host_login                22544 non-null  int64
 21  is_guest_login               22544 non-null  int64
 22  count                        22544 non-null  int64
 23  srv_count                    22544 non-null  int64
 24  serror_rate                  22544 non-null  float64
 25  srv_serror_rate              22544 non-null  float64
 26  rerror_rate                  22544 non-null  float64
 27  srv_rerror_rate              22544 non-null  float64
 28  same_srv_rate                22544 non-null  float64
 29  diff_srv_rate                22544 non-null  float64
 30  srv_diff_host_rate           22544 non-null  float64
 31  dst_host_count               22544 non-null  int64
 32  dst_host_srv_count           22544 non-null  int64
 33  dst_host_same_srv_rate       22544 non-null  float64
 34  dst_host_diff_srv_rate       22544 non-null  float64
 35  dst_host_same_src_port_rate  22544 non-null  float64
 36  dst_host_srv_diff_host_rate  22544 non-null  float64
 37  dst_host_serror_rate         22544 non-null  float64
 38  dst_host_srv_serror_rate     22544 non-null  float64
 39  dst_host_rerror_rate         22544 non-null  float64
 40  dst_host_srv_rerror_rate     22544 non-null  float64
 41  attack                       22544 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 7.2+ MB

In [17]:
#Checking test data for presence of missing values
test_df.isnull().any().value_counts()

False    42
dtype: int64

In [18]:
#Checking genral stats of test data variables whose dta type is object
test_df.describe(include='object').T.head()

               count unique     top   freq
protocol_type  22544      3     tcp  18880
service        22544     64    http   7853
flag           22544     11      SF  14875
attack         22544     38  normal   9711

In [19]:
#This variable is worthless and not contributing anything 
print(train_df['num_outbound_cmds'].value_counts())
print(test_df['num_outbound_cmds'].value_counts())

0    125973
Name: num_outbound_cmds, dtype: int64
0    22544
Name: num_outbound_cmds, dtype: int64

In [20]:
#so removing it from both train and test data
train_df.drop(['num_outbound_cmds'], axis=1, inplace=True)
test_df.drop(['num_outbound_cmds'], axis=1, inplace=True)

In [21]:
# Attack Class Distribution
train_df['attack'].value_counts()

normal             67343
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: attack, dtype: int64

**Multinominal Classification**

In [23]:
names=["duration","protocol_type","service","flag","src_bytes","dst_bytes","land", "wrong_fragment","urgent","hot",
       "num_failed_logins","logged_in", "num_compromised","root_shell","su_attempted","num_root","num_file_creations", 
       "num_shells","num_access_files","num_outbound_cmds","is_host_login", "is_guest_login","count","srv_count",
       "serror_rate", "srv_serror_rate", "rerror_rate","srv_rerror_rate","same_srv_rate", "diff_srv_rate", 
       "srv_diff_host_rate","dst_host_count","dst_host_srv_count","dst_host_same_srv_rate", "dst_host_diff_srv_rate",
       "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
       "dst_host_rerror_rate","dst_host_srv_rerror_rate","attack"] 
train=pd.read_csv('/content/drive/My Drive/Data/KDDTrain+_2.csv', names = names)

In [24]:
test=pd.read_csv('/content/drive/My Drive/Data/KDDTest+_2.csv', names = names)

In [25]:
train.drop(['num_outbound_cmds'], axis=1, inplace=True)
test.drop(['num_outbound_cmds'], axis=1, inplace=True)

In [26]:
DoS_attack_1=['neptune','smurf','back','teardrop','pod','land','apache2','processtable','worm','udpstorm '] 


Probe_attack_2=['satan','ipsweep','portsweep','nmap','mscan','saint'] 


R2L_attack_3=['warezclient','guess_passwd','warezmaster','imap','ftp_write','multihop','phf','spy','snmpguess','mailbomb',
          'snmpgetattack ','httptunnel','named','sendmail','xsnoop','Xlock'] 


U2R_attack_4=['buffer_overflow','rootkit','loadmodule','perl','ps','xterm','sqlattack']

In [27]:
#Creating the dependent variable for train data whci will contain 0 for normal 1 for dos,2 for probe ,3 for R2L and 4 for U2R

train['attack']=train['attack'].apply(lambda x: 1 if x in DoS_attack_1 else 2 if x in Probe_attack_2 else 3 if x in R2L_attack_3 else 4 if x in U2R_attack_4 else 0)

In [28]:
#Creating the dependent variable for test data whci will contain 0 for normal 1 for dos,2 for probe ,3 for R2L and 4 for U2R

test['attack']=test['attack'].apply(lambda x: 1 if x in DoS_attack_1 else 2 if x in Probe_attack_2 else 3 if x in R2L_attack_3 else 4 if x in U2R_attack_4 else 0)

In [29]:
train['attack'].value_counts()

0    67343
1    45927
2    11656
3      995
4       52
Name: attack, dtype: int64

In [30]:
test['attack'].value_counts()

0    9900
1    7165
3    2991
2    2421
4      67
Name: attack, dtype: int64

In [31]:

from sklearn.preprocessing import LabelEncoder
labelencoder1= LabelEncoder()
labelencoder2 = LabelEncoder()
labelencoder3 = LabelEncoder()
le = LabelEncoder()

In [33]:
trainX_1 = train.iloc[:,1].values
trainX_2 = train.iloc[:,2].values
trainX_3 = train.iloc[:,3].values

In [36]:

trainX_1 = labelencoder1.fit_transform(trainX_1)
trainX_1 = trainX_1.reshape(len(trainX_1),1)
trainX_2 = labelencoder2.fit_transform(trainX_2)
trainX_2 = trainX_2.reshape(len(trainX_2),1)
trainX_3 = labelencoder3.fit_transform(trainX_3)
trainX_3 = trainX_3.reshape(len(trainX_3),1)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [37]:
testX_1 = test.iloc[:,1].values
testX_2 = test.iloc[:,2].values
testX_3 = test.iloc[:,3].values

In [39]:
testX_1 = labelencoder1.fit_transform(testX_1)
testX_1 = testX_1.reshape(len(testX_1),1)
testX_2 = labelencoder1.fit_transform(testX_2)
testX_2 = testX_2.reshape(len(testX_2),1)
testX_3 = labelencoder1.fit_transform(testX_3)
testX_3 = testX_3.reshape(len(testX_3),1)

In [42]:
test.head()

   duration protocol_type  ... dst_host_srv_rerror_rate attack
0         0           tcp  ...                     1.00      1
1         0           tcp  ...                     1.00      1
2         2           tcp  ...                     0.00      0
3         0          icmp  ...                     0.00      2
4         1           tcp  ...                     0.71      2

[5 rows x 41 columns]

In [44]:
le = LabelEncoder()
train['protocol_type'] = le.fit_transform(train['protocol_type'])
train['service'] = le.fit_transform(train['service'])
train['flag'] = le.fit_transform(train['flag'])

In [46]:
test['protocol_type'] = le.fit_transform(test['protocol_type'])
test['service'] = le.fit_transform(test['service'])
test['flag'] = le.fit_transform(test['flag'])

In [45]:
train.head()

   duration  protocol_type  ...  dst_host_srv_rerror_rate  attack
0         0              1  ...                      0.00       0
1         0              2  ...                      0.00       0
2         0              1  ...                      0.00       1
3         0              1  ...                      0.01       0
4         0              1  ...                      0.00       0

[5 rows x 41 columns]

In [47]:
test.head()

   duration  protocol_type  ...  dst_host_srv_rerror_rate  attack
0         0              1  ...                      1.00       1
1         0              1  ...                      1.00       1
2         2              1  ...                      0.00       0
3         0              0  ...                      0.00       2
4         1              1  ...                      0.71       2

[5 rows x 41 columns]

In [48]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22544 entries, 0 to 22543
Data columns (total 41 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   duration                     22544 non-null  int64
 1   protocol_type                22544 non-null  int64
 2   service                      22544 non-null  int64
 3   flag                         22544 non-null  int64
 4   src_bytes                    22544 non-null  int64
 5   dst_bytes                    22544 non-null  int64
 6   land                         22544 non-null  int64
 7   wrong_fragment               22544 non-null  int64
 8   urgent                       22544 non-null  int64
 9   hot                          22544 non-null  int64
 10  num_failed_logins            22544 non-null  int64
 11  logged_in                    22544 non-null  int64
 12  num_compromised              22544 non-null  int64
 13  root_shell                   22544 non-null  int64
 14  su_attempted                 22544 non-null  int64
 15  num_root                     22544 non-null  int64
 16  num_file_creations           22544 non-null  int64
 17  num_shells                   22544 non-null  int64
 18  num_access_files             22544 non-null  int64
 19  is_host_login                22544 non-null  int64
 20  is_guest_login               22544 non-null  int64
 21  count                        22544 non-null  int64
 22  srv_count                    22544 non-null  int64
 23  serror_rate                  22544 non-null  float64
 24  srv_serror_rate              22544 non-null  float64
 25  rerror_rate                  22544 non-null  float64
 26  srv_rerror_rate              22544 non-null  float64
 27  same_srv_rate                22544 non-null  float64
 28  diff_srv_rate                22544 non-null  float64
 29  srv_diff_host_rate           22544 non-null  float64
 30  dst_host_count               22544 non-null  int64
 31  dst_host_srv_count           22544 non-null  int64
 32  dst_host_same_srv_rate       22544 non-null  float64
 33  dst_host_diff_srv_rate       22544 non-null  float64
 34  dst_host_same_src_port_rate  22544 non-null  float64
 35  dst_host_srv_diff_host_rate  22544 non-null  float64
 36  dst_host_serror_rate         22544 non-null  float64
 37  dst_host_srv_serror_rate     22544 non-null  float64
 38  dst_host_rerror_rate         22544 non-null  float64
 39  dst_host_srv_rerror_rate     22544 non-null  float64
 40  attack                       22544 non-null  int64
dtypes: float64(15), int64(26)
memory usage: 7.1 MB

In [50]:
train = pd.DataFrame(train)
train.to_csv('KDDtrain_updated.csv')

In [52]:
test = pd.DataFrame(test)
test.to_csv('KDDtest_updated.csv')